apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-microservice
  template:
    metadata:
      labels:
        app: demo-microservice
    spec:
      containers:
      - name: demo-microservice
        image: tariq87/demo-microservice:latest 
        ports:
        - containerPort: 5000

